"""initial"""

import sqlalchemy as sa
from alembic import op

revision = "ab1600c59ce4"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("target", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "members",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("role IN ('reviewer','lead','admin')", name="ck_member_role"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "workspace_lock",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "audit",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("actor_id", sa.String(length=36), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("target", sa.String(length=255), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "edits",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("wiki", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("editor", sa.String(length=255), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("old_rev", sa.Integer(), nullable=False),
        sa.Column("new_rev", sa.Integer(), nullable=False),
        sa.Column("page_id", sa.Integer(), nullable=False),
        sa.Column("namespace", sa.Integer(), nullable=False),
        sa.Column("bot", sa.Boolean(), nullable=False),
        sa.Column("delta", sa.Integer(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("admitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("return_reason", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "status IN ('unclaimed','claimed','ok','flagged','returned','verified_flagged')",
            name="ck_edit_status",
        ),
        sa.CheckConstraint("version >= 1", name="ck_edit_version"),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("wiki", "new_rev"),
    )
    op.create_index(op.f("ix_edits_archived"), "edits", ["archived"], unique=False)
    op.create_index(op.f("ix_edits_occurred_at"), "edits", ["occurred_at"], unique=False)
    op.create_index(op.f("ix_edits_owner_id"), "edits", ["owner_id"], unique=False)
    op.create_index(op.f("ix_edits_status"), "edits", ["status"], unique=False)
    op.create_index(op.f("ix_edits_wiki"), "edits", ["wiki"], unique=False)
    op.create_table(
        "preferences",
        sa.Column("member_id", sa.String(length=36), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("member_id"),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("member_id", sa.String(length=36), nullable=False),
        sa.Column("access_hash", sa.String(length=64), nullable=False),
        sa.Column("refresh_hash", sa.String(length=64), nullable=False),
        sa.Column("access_expires", sa.DateTime(timezone=True), nullable=False),
        sa.Column("refresh_expires", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("access_hash"),
        sa.UniqueConstraint("refresh_hash"),
    )
    op.create_index(op.f("ix_sessions_member_id"), "sessions", ["member_id"], unique=False)
    op.create_table(
        "threads",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("edit_id", sa.String(length=36), nullable=False),
        sa.Column("author_id", sa.String(length=36), nullable=False),
        sa.Column("anchor", sa.JSON(), nullable=False),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["edit_id"],
            ["edits.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_threads_edit_id"), "threads", ["edit_id"], unique=False)
    op.create_table(
        "comments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("thread_id", sa.String(length=36), nullable=False),
        sa.Column("author_id", sa.String(length=36), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["threads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_comments_thread_id"), "comments", ["thread_id"], unique=False)
    # ### end Alembic commands ###
    op.execute(sa.text("INSERT INTO workspace_lock (id) VALUES (1)"))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_comments_thread_id"), table_name="comments")
    op.drop_table("comments")
    op.drop_index(op.f("ix_threads_edit_id"), table_name="threads")
    op.drop_table("threads")
    op.drop_index(op.f("ix_sessions_member_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_table("preferences")
    op.drop_index(op.f("ix_edits_wiki"), table_name="edits")
    op.drop_index(op.f("ix_edits_status"), table_name="edits")
    op.drop_index(op.f("ix_edits_owner_id"), table_name="edits")
    op.drop_index(op.f("ix_edits_occurred_at"), table_name="edits")
    op.drop_index(op.f("ix_edits_archived"), table_name="edits")
    op.drop_table("edits")
    op.drop_table("audit")
    op.drop_table("workspace_lock")
    op.drop_table("members")
    op.drop_table("events")
    # ### end Alembic commands ###
