"""thread_deletion"""

import sqlalchemy as sa
from alembic import op

revision = "e6308d42656d"
down_revision = "38cc10e6c212"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "threads", sa.Column("deleted", sa.Boolean(), server_default=sa.false(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("threads", "deleted")
    # ### end Alembic commands ###
