import React from 'react';
export type Anchor={side:'old'|'new'|'preview',start:number,end:number,exact:string,prefix:string,suffix:string,revisionKey:string};
export type Comment={id:string,anchor:Anchor,body:string,author:string,createdAt:number,resolved:boolean,replies:{id:string,body:string,author:string}[]};
export function fingerprint(s:string){let h=2166136261;for(let i=0;i<s.length;i++)h=Math.imul(h^s.charCodeAt(i),16777619);return (h>>>0).toString(16)}
export function makeAnchor(source:string,side:Anchor['side'],start:number,end:number,revision:string):Anchor {if(start<0||end<=start||end>source.length)throw Error('Choose a non-empty range in one revision.');return {side,start,end,exact:source.slice(start,end),prefix:source.slice(Math.max(0,start-32),start),suffix:source.slice(end,end+32),revisionKey:`${revision}:${side}:${fingerprint(source)}`};}
export function anchorFromRange(range:Range,sources:Record<Anchor['side'],string>,revision:string):Anchor|null{const host=(n:Node)=>((n.nodeType===3?n.parentElement:n as Element)?.closest('[data-review-text]')) as HTMLElement|null;const start=host(range.startContainer),end=host(range.endContainer);if(!start||!end||start.dataset.side!==end.dataset.side)return null;const side=start.dataset.side as Anchor['side'];const part=(el:HTMLElement,node:Node,offset:number)=>{const r=document.createRange();r.selectNodeContents(el);r.setEnd(node,offset);return r.toString().length};const a=Number(start.dataset.sourceStart)+part(start,range.startContainer,range.startOffset),b=Number(end.dataset.sourceStart)+part(end,range.endContainer,range.endOffset);if(b<=a)return null;return makeAnchor(sources[side],side,a,b,revision);}
export function validAnchor(a:Anchor,source:string,revision:string){return a.revisionKey===`${revision}:${a.side}:${fingerprint(source)}`&&source.slice(a.start,a.end)===a.exact;}
export function HighlightedText({text,start,anchors}:{text:string,start:number,anchors:Anchor[]}){const end=start+text.length,bounds=[...new Set([start,end,...anchors.flatMap(a=>a.start<end&&a.end>start?[Math.max(start,a.start),Math.min(end,a.end)]:[])])].sort((a,b)=>a-b);return <>{bounds.slice(0,-1).map((a,i)=>{const b=bounds[i+1],hit=anchors.some(r=>r.start<b&&r.end>a);const value=text.slice(a-start,b-start);return hit?<mark key={a} className="bg-yellow-200 dark:bg-yellow-800 text-inherit rounded-sm">{value}</mark>:<React.Fragment key={a}>{value}</React.Fragment>})}</>}
export type RenderNode={kind:'text',text:string}|{kind:'element',tag:string,children:RenderNode[]};
export const previewTree:RenderNode={kind:'element',tag:'div',children:[{kind:'text',text:'My Name is '},{kind:'element',tag:'b',children:[{kind:'text',text:'Ahmed'}]}]};
export const PREVIEW_TEXT='My Name is Ahmed';
export function renderSafeTree(node:RenderNode,anchors:Anchor[],offset={value:0},key='root'):React.ReactNode{if(node.kind==='text'){const start=offset.value;offset.value+=node.text.length;return <HighlightedText key={key} text={node.text} start={start} anchors={anchors}/>;}if(!['div','p','b','strong','i','em'].includes(node.tag))return null;return React.createElement(node.tag,{key},node.children.map((n,i)=>renderSafeTree(n,anchors,offset,`${key}-${i}`)));}
