import React,{useMemo,useRef,useState,useCallback,useEffect,useId} from 'react';
import {AgGridReact} from 'ag-grid-react';
import {AllCommunityModule,ModuleRegistry,themeQuartz,type ColDef,type ICellRendererParams,type GridApi,type RowSelectionOptions,type SelectionColumnDef} from 'ag-grid-community';
import {Button} from './components/ui/button';
import {Columns3,X} from 'lucide-react';
ModuleRegistry.registerModules([AllCommunityModule]);
type Props=React.HTMLAttributes<HTMLElement>&{'data-value'?:string|number,'data-row-id'?:string|number};
export const TableHeader=(_props:Props)=>null;
export const TableBody=(_props:Props)=>null;
export const TableRow=(_props:Props)=>null;
export const TableHead=(_props:Props)=>null;
export const TableCell=(_props:Props)=>null;
function nodes(children:React.ReactNode):React.ReactElement<Props>[] {return React.Children.toArray(children).flatMap(child=>React.isValidElement<Props>(child)?child.type===React.Fragment?nodes(child.props.children):[child]:[])}
function textOf(value:React.ReactNode):string{return React.Children.toArray(value).map(x=>React.isValidElement<Props>(x)?textOf(x.props.children):String(x)).join(' ').replace(/\s+/g,' ').trim()}
type Row={id:string,cells:React.ReactElement<Props>[],className?:string};
const theme=themeQuartz.withParams({backgroundColor:'hsl(var(--card))',foregroundColor:'hsl(var(--foreground))',headerBackgroundColor:'hsl(var(--muted))',headerTextColor:'hsl(var(--muted-foreground))',borderColor:'hsl(var(--border))',accentColor:'hsl(var(--primary))',fontFamily:'inherit',fontSize:13,wrapperBorder:false,spacing:6});
function Cell({data,colDef}:ICellRendererParams<Row>){const cell=data?.cells[Number(colDef?.colId)];return cell?<div className={`py-2 w-full ${cell.props.className||''}`}>{cell.props.children}</div>:null}
const numeric=new Set(['Change','Active claims','Marked OK','Pending verification','Verified flags','Total reviewed','Observed edits']);
const defaultColumns:ColDef<Row>={suppressKeyboardEvent:p=>p.event.key==='Tab'&&p.event.target!==p.event.currentTarget};
const actions=new Set(['Select','Actions','Diff']);
const multiSelection:RowSelectionOptions<Row>={mode:'multiRow',selectAll:'currentPage',checkboxes:true,headerCheckbox:true,enableClickSelection:false};
const selectionColumn:SelectionColumnDef={headerName:'Select',headerTooltip:'Select all edits on the current page',width:80,minWidth:80,maxWidth:80,resizable:false,suppressMovable:true};
const selectionLocale={ariaHeaderSelection:'Select all edits on current page'};
export function Table({children,className,pageSize=12,onPageChanged,onFilteredRowsChange,onInteractionChanged,onSelectedRowsChange,resetPageKey,...props}:Props&{pageSize?:number,onPageChanged?:(page:number)=>void,onFilteredRowsChange?:(ids:string[])=>void,onInteractionChanged?:(busy:boolean)=>void,onSelectedRowsChange?:(ids:string[])=>void,resetPageKey?:unknown}){
 const parts=nodes(children),header=parts.find(p=>p.type===TableHeader),body=parts.find(p=>p.type===TableBody);const heads=nodes(nodes(header?.props.children)[0]?.props.children);const headerKey=JSON.stringify(heads.map(head=>[textOf(head.props.children),head.props.className]));
 const panelId=useId(),toggleRef=useRef<HTMLButtonElement>(null);const closeColumns=()=>{setChooser(false);toggleRef.current?.focus()};const api=useRef<GridApi<Row>|null>(null),callbacks=useRef({onPageChanged,onFilteredRowsChange,onInteractionChanged,onSelectedRowsChange});callbacks.current={onPageChanged,onFilteredRowsChange,onInteractionChanged,onSelectedRowsChange};const [chooser,setChooser]=useState(false),[menuOpen,setMenuOpen]=useState(false),[hidden,setHidden]=useState<string[]>([]),[page,setPage]=useState(1),[pages,setPages]=useState(1),[count,setCount]=useState(0);
 const columns=useMemo<ColDef<Row>[]>(()=>heads.map((head,i)=>{const label=textOf(head.props.children),action=actions.has(label),number=numeric.has(label);return {colId:String(i),headerName:label,headerClass:head.props.className,valueGetter:p=>{const cell=p.data?.cells[i];const raw=cell?.props['data-value']??textOf(cell?.props.children);return number?Number(String(raw).replace(/[^\d.+-]/g,'')):raw},cellRenderer:Cell,cellDataType:number?'number':'text',filter:action?false:number?'agNumberColumnFilter':'agTextColumnFilter',filterParams:{debounceMs:200},floatingFilter:false,flex:label==='Page / edit'?3:1,minWidth:label==='Select'?65:['Wiki','Change','Time'].includes(label)?110:label==='Page / edit'?270:155,autoHeight:true,wrapText:true,resizable:true,sortable:!action,suppressMovable:action,lockVisible:action,suppressHeaderMenuButton:true,suppressHeaderFilterButton:action}}),[headerKey]);
 const rows=useMemo(()=>nodes(body?.props.children).map((row,i)=>({id:String(row.props['data-row-id']??row.key??i),cells:nodes(row.props.children),className:row.props.className})),[body?.props.children]);
 const sync=useCallback(()=>{const grid=api.current;if(!grid||grid.isDestroyed())return;const nextPage=grid.paginationGetCurrentPage()+1;setPage(nextPage);setPages(Math.max(1,grid.paginationGetTotalPages()));setCount(grid.getDisplayedRowCount());callbacks.current.onPageChanged?.(nextPage);if(callbacks.current.onFilteredRowsChange){const ids:string[]=[];grid.forEachNodeAfterFilterAndSort(n=>{if(n.data)ids.push(n.data.id)});callbacks.current.onFilteredRowsChange(ids)}},[]);
 const syncColumns=useCallback(()=>{const grid=api.current;if(grid&&!grid.isDestroyed())setHidden(grid.getColumnState().filter(c=>c.hide).map(c=>c.colId))},[]);
 useEffect(()=>{callbacks.current.onInteractionChanged?.(chooser||menuOpen)},[chooser,menuOpen]);useEffect(()=>{api.current?.paginationGoToFirstPage()},[resetPageKey]);
 function toggle(id:string,checked:boolean){const grid=api.current;if(!grid)return;const dataColumns=columns.filter(c=>!actions.has(c.headerName||''));if(!checked&&dataColumns.filter(c=>!hidden.includes(c.colId!)).length<=1)return;grid.setColumnsVisible([id],checked);syncColumns()}
 return <div {...props} className={`data-grid ${className||''}`}><div className="grid-workspace"><div className="grid-viewport"><AgGridReact<Row> theme={theme} rowSelection={onSelectedRowsChange?multiSelection:undefined} selectionColumnDef={selectionColumn} localeText={selectionLocale} onSelectionChanged={e=>callbacks.current.onSelectedRowsChange?.([...new Set(e.api.getSelectedRows().map(row=>row.id))])} rowData={rows} columnDefs={columns} getRowId={p=>p.data.id} getRowClass={p=>p.data?.className} domLayout="normal" headerHeight={42} rowHeight={48} rowBuffer={12} suppressColumnVirtualisation ensureDomOrder animateRows={false} pagination paginationPageSize={pageSize} paginationPageSizeSelector={false} suppressPaginationPanel suppressDragLeaveHidesColumns suppressScrollOnNewData popupParent={document.body} onColumnMenuVisibleChanged={e=>setMenuOpen(e.visible)} tooltipShowDelay={300} onGridReady={e=>{api.current=e.api;e.api.setGridAriaProperty('label',props['aria-label']||'Data table');sync()}} onRowDataUpdated={sync} onFilterChanged={sync} onSortChanged={sync} onPaginationChanged={sync} onColumnVisible={syncColumns} defaultColDef={defaultColumns}/></div>{chooser&&<aside id={panelId} className="grid-columns-panel" aria-label="Table columns" onKeyDown={e=>{if(e.key==='Escape'){e.stopPropagation();closeColumns()}}}><div className="flex items-center justify-between mb-3"><h3 className="text-sm font-semibold">Columns</h3><Button size="icon" variant="ghost" aria-label="Close columns" onClick={closeColumns}><X className="h-4 w-4"/></Button></div><p className="text-xs text-muted-foreground mb-4">Show or hide columns. Drag a header to reorder; drag its edge to resize.</p><div className="space-y-3">{columns.filter(c=>!actions.has(c.headerName||'')).map(c=><label key={c.colId} className="flex gap-2 items-center text-xs"><input type="checkbox" checked={!hidden.includes(c.colId!)} onChange={e=>toggle(c.colId!,e.target.checked)}/>{c.headerName}</label>)}</div><Button variant="outline" size="sm" className="mt-4" onClick={()=>{api.current?.resetColumnState();syncColumns()}}>Reset columns</Button></aside>}<div className="grid-side-tabs"><button ref={toggleRef} aria-label="Columns" title="Columns" aria-expanded={chooser} aria-controls={panelId} onClick={()=>setChooser(!chooser)} className={chooser?'bg-muted':''}><Columns3 className="h-4 w-4"/><span>Columns</span></button></div></div><div className="grid-pagination"><span>{count} rows · Page {page} of {pages}</span><div className="flex gap-1"><Button variant="ghost" size="sm" onClick={()=>api.current?.setFilterModel(null)}>Clear filters</Button><Button variant="ghost" size="sm" aria-label="Previous page" disabled={page<=1} onClick={()=>api.current?.paginationGoToPreviousPage()}>Previous</Button><Button variant="ghost" size="sm" aria-label="Next page" disabled={page>=pages} onClick={()=>api.current?.paginationGoToNextPage()}>Next</Button></div></div></div>
}
