import React,{useEffect,useState,useRef} from 'react';
import {Button} from './components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from './components/ui/dialog';
import {recentEdits,revisionPair,validateCompare,eventToEdit,STREAM,WIKIS,type ApiCheck} from './wiki';
import type {Edit} from './model';
type Props={shared?:boolean,enabled?:boolean,offline:boolean,ingest:(edits:Edit[],count:boolean)=>void,onConnection?:(connected:boolean)=>void,onStatusChange?:(status:string)=>void,open:boolean,onOpenChange:(open:boolean)=>void,accountControls?:React.ReactNode,sourceControls?:React.ReactNode};
export function LiveData({shared=false,enabled=true,offline,ingest,onConnection,onStatusChange,open,onOpenChange,accountControls,sourceControls}:Props){
 const [status,setStatus]=useState('Connecting'),[checks,setChecks]=useState<ApiCheck[]>([]),[error,setError]=useState(''),[retry,setRetry]=useState(0),[testing,setTesting]=useState(false),[started]=useState(Date.now());const callbacks=useRef({ingest,onConnection,onStatusChange});callbacks.current={ingest,onConnection,onStatusChange};
 useEffect(()=>{callbacks.current.onStatusChange?.(enabled?status:'Example data');if(enabled)callbacks.current.onConnection?.(status==='Connected')},[status,enabled]);
 useEffect(()=>{const listen=(e:Event)=>setChecks(x=>[(e as CustomEvent<ApiCheck>).detail,...x.filter(c=>c.url!==(e as CustomEvent<ApiCheck>).detail.url)].slice(0,8));window.addEventListener('wiki-api-check',listen);return()=>window.removeEventListener('wiki-api-check',listen)},[]);
 useEffect(()=>{if(!enabled)return;if(offline){setStatus('Browser offline');return}setStatus('Connecting');setError('');const controller=new AbortController();let buffer:Edit[]=[];let source:EventSource|undefined;let stopped=false;let since:string|null=null;try{const saved=sessionStorage.getItem('patrol-stream-since');if(saved)since=new Date(Math.max(started-60000,Date.parse(saved)||started)).toISOString()}catch{}
  void(async()=>{for(const wiki of WIKIS){try{const items=await recentEdits(wiki,controller.signal);if(!stopped)callbacks.current.ingest(items,false)}catch(e){if(!controller.signal.aborted)setError((e as Error).message)}}})();
  if(typeof EventSource==='undefined'){setStatus('Stream unavailable');setError('This browser does not provide EventSource.')}else{source=new EventSource(STREAM+(since?`?since=${encodeURIComponent(since)}`:''));source.onopen=()=>{if(!stopped){setStatus('Connected');setError('')}};source.onerror=()=>{if(!stopped)setStatus(source?.readyState===2?'Stream closed':'Reconnecting')};source.onmessage=event=>{if(stopped)return;try{const edit=eventToEdit(JSON.parse(event.data));if(edit){buffer.push(edit);if(buffer.length>500)buffer.shift();try{sessionStorage.setItem('patrol-stream-since',new Date(Math.max(started-60000,edit.time-2000)).toISOString())}catch{}}}catch{setError('An invalid stream event was ignored.')}}}
  const flush=()=>{if(buffer.length){const batch=buffer;buffer=[];callbacks.current.ingest(batch,true)}};const timer=setInterval(flush,1000);return()=>{stopped=true;controller.abort();source?.close();clearInterval(timer);flush()}
 },[enabled,offline,retry]);
 async function check(){setTesting(true);setError('');try{const edits=await recentEdits('en');callbacks.current.ingest(edits,false);const edit=edits.find(e=>!!e.oldRev);if(!edit)throw Error('No comparison candidate in this response.');await revisionPair(edit);await validateCompare(edit)}catch(e){setError((e as Error).message)}finally{setTesting(false)}}
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-2xl max-h-[85vh] overflow-auto"><DialogHeader><DialogTitle>Dev mode</DialogTitle><DialogDescription>Inspect browser connections and public API responses. Closing this dialog keeps the stream running.</DialogDescription></DialogHeader>{accountControls}<div className="flex items-center gap-3"><span className="text-sm font-medium">Data source</span>{sourceControls}</div><div className="rounded-lg border p-4 space-y-3"><p className="font-medium">{enabled?`Wikimedia: ${status}`:'Example data · no Wikimedia connection'}</p><p className="text-xs text-muted-foreground">EN · AR · JA article edits. Public reads only. The browser’s actual network and EventSource states determine connection status.</p><div className="flex gap-2"><Button size="sm" variant="outline" disabled={!enabled||offline||testing} aria-busy={testing} onClick={check}>Check real APIs</Button><Button size="sm" variant="outline" disabled={!enabled||offline} onClick={()=>setRetry(x=>x+1)}>Reconnect stream</Button></div>{error&&<p role="alert" className="text-sm text-destructive">{error} No example data is substituted.</p>}</div><p className="text-xs text-muted-foreground">The feed includes a recent snapshot. Charts count unique stream edits, excluding that snapshot. Partial intervals retain observed counts. {shared?'Admitted edits, claims, notes, members and audit records are saved in the team database.':'The unclaimed queue is local to this browser. Team claims, notes, members and audit records are browser-local simulations.'}</p><div><h3 className="text-sm font-medium mb-2">API checks</h3>{!checks.length&&<p className="text-xs text-muted-foreground">No requests recorded yet.</p>}<ul className="text-xs space-y-2">{checks.map(c=><li key={c.url}><a href={c.url} target="_blank" rel="noreferrer" className="underline">{c.operation}</a> — {c.status}</li>)}</ul></div><div className="flex flex-wrap gap-3 text-xs">{[['EventStreams','https://wikitech.wikimedia.org/wiki/Event_Platform/EventStreams_HTTP_Service'],['Revisions','https://www.mediawiki.org/wiki/API:Revisions'],['Compare','https://www.mediawiki.org/wiki/API:Compare'],['RecentChanges','https://www.mediawiki.org/wiki/API:RecentChanges']].map(([name,url])=><a key={name} href={url} target="_blank" rel="noreferrer" className="underline">{name}</a>)}</div></DialogContent></Dialog>
}
